"""Enumerate SID ADSR combinations via pyresidfp; report redundancy."""

import hashlib
import multiprocessing as mp
import os
import unittest
from collections import defaultdict
from datetime import timedelta
from pathlib import Path

import numpy as np
from pyresidfp import SoundInterfaceDevice

SAMPLING_FREQUENCY = 8_000

REG_FREQ_LO = 0
REG_FREQ_HI = 1
REG_CTRL = 4
REG_AD = 5
REG_SR = 6
REG_VOLUME = 24

CTRL_GATE_ON = 0b00100001
CTRL_GATE_OFF = 0b00100000

FREQ_LO = 8
FREQ_HI = 8

SETTLE_MS = 1000
GATE_ON_MS = 200
GATE_OFF_MS = 200


def _render_one(ad_sr):
    """Render one (AD, SR) pair through pyresidfp. Returns
    ``(ad, sr, sample_bytes)``. Constructs a fresh SID per call so
    no state leaks between combos.
    """
    ad, sr = ad_sr
    sid = SoundInterfaceDevice(sampling_frequency=SAMPLING_FREQUENCY)
    sid.write_register(REG_VOLUME, 15)
    sid.write_register(REG_FREQ_LO, FREQ_LO)
    sid.write_register(REG_FREQ_HI, FREQ_HI)
    sid.write_register(REG_AD, ad)
    sid.write_register(REG_SR, sr)
    sid.clock(timedelta(milliseconds=SETTLE_MS))
    sid.write_register(REG_CTRL, CTRL_GATE_ON)
    on_samples = sid.clock(timedelta(milliseconds=GATE_ON_MS))
    sid.write_register(REG_CTRL, CTRL_GATE_OFF)
    off_samples = sid.clock(timedelta(milliseconds=GATE_OFF_MS))
    arr = np.asarray(list(on_samples) + list(off_samples), dtype=np.int16)
    return ad, sr, arr.tobytes()


def _render_hash(ad_sr):
    ad, sr, sample_bytes = _render_one(ad_sr)
    return ad, sr, hashlib.md5(sample_bytes).hexdigest()


class TestADSREquivalence(unittest.TestCase):
    def test_render_smoke(self):
        """pyresidfp renders our test note shape with the expected
        sample-count layout."""
        ad, sr, sample_bytes = _render_one((0x11, 0xF0))
        self.assertEqual(ad, 0x11)
        self.assertEqual(sr, 0xF0)
        n_samples = len(sample_bytes) // 2
        expected = SAMPLING_FREQUENCY * (GATE_ON_MS + GATE_OFF_MS) / 1000
        self.assertGreater(n_samples, expected * 0.95)
        self.assertLess(n_samples, expected * 1.05)

    @unittest.skipUnless(
        os.environ.get("RUN_FULL_ADSR_ENUM"),
        "set RUN_FULL_ADSR_ENUM=1 to enumerate all 65,536 ADSR combos",
    )
    def test_full_enumeration_redundancy(self):
        """Exhaustive sweep + report."""
        combos = [(ad, sr) for ad in range(256) for sr in range(256)]
        with mp.Pool() as pool:
            hash_results = pool.map(_render_hash, combos, chunksize=64)

        classes = defaultdict(list)
        for ad, sr, h in hash_results:
            classes[h].append((ad, sr))

        reps = [members[0] for members in classes.values()]
        with mp.Pool() as pool:
            rep_samples = pool.map(_render_one, reps, chunksize=64)

        report_path = Path(__file__).resolve().parent / "design"
        report_path.mkdir(exist_ok=True)
        report_file = report_path / "adsr_equivalence_report.md"
        _write_report(report_file, classes, rep_samples)
        self.assertTrue(report_file.exists())


def _write_report(report_file, classes, rep_samples):
    """Render the equivalence-class summary to a markdown report."""
    n_combos = sum(len(c) for c in classes.values())
    n_classes = len(classes)
    class_sizes = sorted((len(c) for c in classes.values()), reverse=True)
    saved = sum(s - 1 for s in class_sizes)

    lines = []
    lines.append("# SID ADSR redundancy enumeration\n\n")
    lines.append(
        "Generated by `integration_tests/test_adsr_equivalence.py` "
        "(`RUN_FULL_ADSR_ENUM=1 pytest -k full_enumeration`).\n\n"
    )
    lines.append(
        f"**Method**: render each (AD, SR) at {SAMPLING_FREQUENCY} Hz "
        f"with FREQ_LO/HI={FREQ_LO}, triangle waveform; "
        f"{SETTLE_MS} ms idle settle, gate-on for {GATE_ON_MS} ms, "
        f"then gate-off for {GATE_OFF_MS} ms via pyresidfp. Group by "
        f"md5 hash of the int16 sample array.\n\n"
    )
    lines.append(
        f"**Headline numbers**:\n"
        f"- Total combinations: **{n_combos}** (256 AD x 256 SR)\n"
        f"- Distinct exact-equivalence classes: **{n_classes}**\n"
        f"- Combinations foldable into a representative (size > 1 in class): "
        f"**{saved}** ({saved / n_combos:.1%})\n"
        f"- Largest class size: **{class_sizes[0]}**\n\n"
    )

    lines.append("## Class-size histogram\n\n")
    bucket = defaultdict(int)
    for size in class_sizes:
        if size <= 4:
            bucket[size] += 1
        elif size <= 16:
            bucket["5-16"] += 1
        elif size <= 64:
            bucket["17-64"] += 1
        else:
            bucket["65+"] += 1
    lines.append("| class size | count |\n|---|---:|\n")
    for label in (1, 2, 3, 4, "5-16", "17-64", "65+"):
        lines.append(f"| {label} | {bucket.get(label, 0)} |\n")

    lines.append("\n## Top 30 exact equivalence classes\n\n")
    lines.append(
        "Each row: a class of (AD, SR) pairs producing **byte-identical** "
        "audio under this test setup. ``A``, ``D``, ``S``, ``R`` columns "
        "show the nibble ranges spanned by the class members.\n\n"
    )
    lines.append(
        "| size | A | D | S | R | sample (AD, SR) |\n|---:|---|---|---|---|---|\n"
    )
    sorted_classes = sorted(classes.values(), key=len, reverse=True)
    for cls in sorted_classes[:30]:
        a_set = sorted({ad >> 4 for ad, _ in cls})
        d_set = sorted({ad & 0xF for ad, _ in cls})
        s_set = sorted({sr >> 4 for _, sr in cls})
        r_set = sorted({sr & 0xF for _, sr in cls})
        sample_ad, sample_sr = cls[0]
        lines.append(
            f"| {len(cls)} | {_nibble_range(a_set)} | {_nibble_range(d_set)} "
            f"| {_nibble_range(s_set)} | {_nibble_range(r_set)} "
            f"| (0x{sample_ad:02x}, 0x{sample_sr:02x}) |\n"
        )

    lines.append("\n## Empirical S=15 collapse check\n\n")
    lines.append(
        "Hypothesis from the data sheet: when ``S=15`` (sustain == peak), "
        "the decay phase has zero distance to traverse, so all 16 ``D`` "
        "values should produce identical audio. We test this by counting, "
        "for each (A, R), how many distinct exact-classes the 16 ``D`` "
        "values land in (an ideal-collapsed case is 1; no collapse is 16).\n\n"
    )
    cls_index = {}
    for cls_id, cls_members in enumerate(classes.values()):
        for ad_sr in cls_members:
            cls_index[ad_sr] = cls_id

    s15_collapse_rows = []
    for r in range(16):
        sr = (15 << 4) | r
        for a in range(16):
            cls_ids = {cls_index.get(((a << 4) | d, sr)) for d in range(16)}
            cls_ids.discard(None)
            s15_collapse_rows.append((a, r, len(cls_ids)))
    full = sum(1 for *_, n in s15_collapse_rows if n == 1)
    partial = sum(1 for *_, n in s15_collapse_rows if 1 < n < 16)
    none = sum(1 for *_, n in s15_collapse_rows if n == 16)
    lines.append(
        f"Across all 256 `(A, R)` pairs at S=15:\n"
        f"- **{full}** pairs collapse fully (1 class for all 16 D values)\n"
        f"- **{partial}** pairs collapse partially (2-15 classes)\n"
        f"- **{none}** pairs do not collapse (16 distinct classes)\n\n"
    )
    if full < 256:
        lines.append(
            "> The byte-equal collapse hypothesis fails for "
            f"{256 - full} of 256 (A, R) pairs in this setup.\n\n"
        )

    lines.append("## Near-equivalence (representative pairwise L-inf)\n\n")
    lines.append(
        "For each pair of class representatives, the L-inf distance "
        "between their sample arrays. Sample range is int16 "
        "(-32768..32767); each threshold below corresponds to a coarse "
        "audibility floor.\n\n"
    )
    sample_arrays = [
        ((ad, sr), np.frombuffer(b, dtype=np.int16)) for ad, sr, b in rep_samples
    ]

    thresholds = [4, 16, 64, 256, 1024]
    threshold_counts = {t: 0 for t in thresholds}
    n_reps = len(sample_arrays)
    if n_reps > 2000:
        rng = np.random.default_rng(0)
        idx = rng.choice(n_reps, size=2000, replace=False)
        sampled = [sample_arrays[i] for i in idx]
    else:
        sampled = sample_arrays
    n = len(sampled)
    pair_count = n * (n - 1) // 2
    lines.append(
        f"Representative-set size: **{n_reps}**; pairwise L-inf "
        f"computed across **{n}** representatives "
        f"({'random sample' if n < n_reps else 'exhaustive'}, "
        f"{pair_count} pairs).\n\n"
    )
    for i in range(n):
        _, a_arr = sampled[i]
        for j in range(i + 1, n):
            _, b_arr = sampled[j]
            m = min(len(a_arr), len(b_arr))
            dist = int(
                np.max(np.abs(a_arr[:m].astype(np.int32) - b_arr[:m].astype(np.int32)))
            )
            for t in thresholds:
                if dist <= t:
                    threshold_counts[t] += 1
    lines.append(
        "| L-inf threshold | pairs at-or-below | fraction of pairs |\n|---:|---:|---:|\n"
    )
    for t in thresholds:
        c = threshold_counts[t]
        frac = c / pair_count if pair_count else 0
        lines.append(f"| <= {t} | {c} | {frac:.2%} |\n")

    lines.append("\n## Conclusions\n\n")
    if full < 256:
        lines.append(
            "- The naive **S=15 -> D irrelevant** rule fails at the "
            "byte level in resid emulation. Not safe as a static "
            "canonicalisation in the encoder.\n"
        )
    if saved / n_combos < 0.5:
        lines.append(
            f"- Only {saved / n_combos:.1%} of ADSR combinations are "
            f"foldable via byte-identical equivalence in this setup. "
            f"Limited leverage for redundancy elimination at the "
            f"alphabet level.\n"
        )
    lines.append(
        "- Near-equivalence (L-inf distance below a perceptual "
        "threshold) is more permissive but lossy by definition; any "
        "encoder using it would change the audio output. Worth "
        "considering only for an explicit lossy-path Path E "
        "(matching the existing Path A/D nearest-val substitutions).\n"
    )

    report_file.write_text("".join(lines))


def _nibble_range(values):
    if len(values) == 16:
        return "0x0..0xF (all)"
    if len(values) == 1:
        return f"0x{values[0]:x}"
    return ",".join(f"0x{v:x}" for v in values)


if __name__ == "__main__":
    unittest.main()
